image: ubuntu

environment:
  APPVEYOR_SSH_BLOCK: true
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA1vhEsFkLNp3J0IWXJK1ukScKTFuWCeyIh8CCf/Q255uoBFF23+EfTw5qlLBPQemKHcVKANGlAOdJ21M1EnL0YAZvW6Nw73SgPM9ZaZRPDu9HiOAcPR01mVhiptmRfr8F1SuyMg7M92/b5vdlyMihrdvvEfhQ9ied2vugHAzU8p1JqTVZlmIfqzbALKYmkP90wy4knxe5QNbqi6x8gHdWEYwvM9/NHAvZwPSzcwwlhzmXYqe2P6Xie7+omATnZ0KNwC/AWdou0WjPadxZU+LgDo5dWQZXwK6Y+LIyf3Nay0sWx+8frodKAFXcRNiqEsAGjUwIDRtmD0qeRHNA6TMCNw== rsa-key-20180328

install:
- sh: sudo ufw deny OpenSSH

test_script:
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

build: off
